### ISSUE TITLE
Please update the documentation to reflect the current state of fedmsg topic names

### ISSUE THREAD

**Issue by thrix** [CentOS-PaaS-SIG/upstream-fedora-pipeline#83]
Fedmsg now contains allpackages-build and allpackages-pr, please update the docs to reflect this.

Note that there is a corresponding fedmsg meta update issue here:
https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/issues/484

**Comment by johnbieren** [comment]
Fixed in https://github.com/CentOS-PaaS-SIG/upstream-fedora-pipeline/pull/86
